export const indianStates = [
    { value: "AN", label: "Andaman and Nicobar Islands", description: "A group of islands in the Bay of Bengal known for their pristine beaches and marine life." },
    { value: "AP", label: "Andhra Pradesh", description: "A southeastern coastal state known for its rich cultural heritage, temples, and spicy cuisine." },
    { value: "AR", label: "Arunachal Pradesh", description: "A northeastern state known for its breathtaking landscapes, diverse tribes, and rich biodiversity." },
    { value: "AS", label: "Assam", description: "A state known for its tea gardens, wildlife sanctuaries, and the mighty Brahmaputra river." },
    { value: "BR", label: "Bihar", description: "A state in eastern India known for its historical significance, rich culture, and educational institutions." },
    { value: "CH", label: "Chandigarh", description: "A union territory serving as the capital of both Punjab and Haryana, known for its well-planned architecture and gardens." },
    { value: "CT", label: "Chhattisgarh", description: "A central-eastern state known for its natural beauty, tribal culture, and mineral resources." },
    { value: "DN", label: "Dadra and Nagar Haveli and Daman and Diu", description: "A union territory formed by merging two former Portuguese colonies known for their scenic beauty and colonial architecture." },
    { value: "DL", label: "Delhi", description: "The capital territory of India known for its historical monuments, bustling markets, and diverse culture." },
    { value: "GA", label: "Goa", description: "A coastal state known for its beautiful beaches, Portuguese architecture, and vibrant nightlife." },
    { value: "GJ", label: "Gujarat", description: "A western state known for its rich history, vibrant festivals, and contributions to trade and industry." },
    { value: "HR", label: "Haryana", description: "A northern state known for its agricultural prosperity, rich cultural heritage, and industrial development." },
    { value: "HP", label: "Himachal Pradesh", description: "A northern state known for its scenic beauty, hill stations, and adventure tourism." },
    { value: "JK", label: "Jammu and Kashmir", description: "A northernmost state known for its stunning landscapes, diverse culture, and religious significance." },
    { value: "JH", label: "Jharkhand", description: "A state in eastern India known for its mineral wealth, lush forests, and tribal heritage." },
    { value: "KA", label: "Karnataka", description: "A southern state known for its technological prowess, historical monuments, and diverse culture." },
    { value: "KL", label: "Kerala", description: "A southwestern state known for its backwaters, lush greenery, and rich cultural heritage." },
    { value: "LA", label: "Ladakh", description: "A union territory known for its stark landscapes, Buddhist monasteries, and adventure tourism." },
    { value: "LD", label: "Lakshadweep", description: "A group of islands in the Arabian Sea known for their pristine beaches, coral reefs, and marine biodiversity." },
    { value: "MP", label: "Madhya Pradesh", description: "A central state known for its historical monuments, wildlife reserves, and vibrant tribal culture." },
    { value: "MH", label: "Maharashtra", description: "A western state known for its cosmopolitan cities, Bollywood film industry, and rich cultural heritage." },
    { value: "MN", label: "Manipur", description: "A northeastern state known for its scenic beauty, vibrant festivals, and rich cultural heritage." },
    { value: "ML", label: "Meghalaya", description: "A northeastern state known for its lush greenery, waterfalls, and unique tribal culture." },
    { value: "MZ", label: "Mizoram", description: "A northeastern state known for its scenic beauty, vibrant festivals, and rich tribal culture." },
    { value: "NL", label: "Nagaland", description: "A northeastern state known for its scenic beauty, vibrant festivals, and unique tribal culture." },
    { value: "OD", label: "Odisha", description: "An eastern state known for its ancient temples, pristine beaches, and rich cultural heritage." },
    { value: "PY", label: "Puducherry", description: "A union territory known for its French colonial architecture, serene beaches, and spiritual atmosphere." },
    { value: "PB", label: "Punjab", description: "A northern state known for its fertile land, rich cultural heritage, and delicious cuisine." },
    { value: "RJ", label: "Rajasthan", description: "A northwestern state known for its royal palaces, vibrant festivals, and desert landscapes." },
    { value: "SK", label: "Sikkim", description: "A northeastern state known for its stunning landscapes, Buddhist monasteries, and adventure tourism." },
    { value: "TN", label: "Tamil Nadu", description: "A southern state known for its ancient temples, classical dance forms, and rich culinary tradition." },
    { value: "TS", label: "Telangana", description: "A southern state known for its historical monuments, rich cultural heritage, and IT industry." },
    { value: "TR", label: "Tripura", description: "A northeastern state known for its lush greenery, vibrant festivals, and unique tribal culture." },
    { value: "UP", label: "Uttar Pradesh", description: "A northern state known for its historical monuments, religious significance, and vibrant culture." },
    { value: "UK", label: "Uttarakhand", description: "A northern state known for its scenic beauty, pilgrimage sites, and adventure tourism." },
    { value: "WB", label: "West Bengal", description: "An eastern state known for its rich cultural heritage, intellectual legacy, and delicious cuisine." },
  ];
  